{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Neural Network\n",
    "\n",
    "Jay Urbain, PhD"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Multi-layer Perceptron (MLP)** is a supervised learning algorithm that learns a function $f(\\cdot): R^m \\rightarrow R^o$ by training on a dataset, where $m$ is the number of dimensions for input and $o$ is the the number of dimensions for output. Given a set of features $X = {x_1, x_2, ..., x_m}$ and a target $y$, it can learn a non-linear function approximator for either classification or regression. It is different from logistic regression, in that between the input and the output layer, there can be one or more non-linear layers, called hidden layers. \n",
    "\n",
    "<img src=\"multilayerperceptron_network.png\">"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The leftmost layer, known as the input layer, consists of a set of neurons $\\{x_i | x_1, x_2, ..., x_m\\}$ representing the input features. Each neuron in the hidden layer transforms the values from the previous layer with a weighted linear summation $w_1x_1 + w_2x_2 + ... + w_mx_m$, followed by a non-linear activation function $g(\\cdot):R \\rightarrow R$ - like the hyperbolic tangent or logistic function. The output layer receives the values from the last hidden layer and transforms them into output values.  \n",
    "The module contains the public attributes *coefs_* and *intercepts_*. *coefs_* is a list of weight matrices, where weight matrix at index $i$ represents the weights between layer $i$ and layer $i+1$. *intercepts_* is a list of bias vectors, where the vector at index $i$ represents the bias values added to layer $i+1$. \n",
    "\n",
    "The advantages of Multi-layer Perceptron are:\n",
    "- Capability to learn non-linear models.\n",
    "- Capability to learn models in real-time (on-line learning) using partial_fit.  \n",
    "\n",
    "The disadvantages of Multi-layer Perceptron (MLP) include:\n",
    "- MLP with hidden layers have a non-convex loss function where there exists more than one local minimum. Therefore different random weight initializations can lead to different validation accuracy.  \n",
    "- MLP requires tuning a number of hyperparameters such as the number of hidden neurons, layers, and iterations.  \n",
    "- MLP is sensitive to feature scaling."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Classification\n",
    "\n",
    "Class *MLPClassifier* implements a multi-layer perceptron (MLP) algorithm that trains using *Backpropagation*. \n",
    "\n",
    "MLP trains on two arrays: array $X$ of size *(n_samples, n_features)*, which holds the training samples represented as floating point feature vectors; and array $y$ of size *(n_samples,)*, which holds the target values *(class labels)* for the training samples:\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "__init__() got an unexpected keyword argument 'algorithm'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-2-276ec56731fa>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     10\u001b[0m \u001b[0mX\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0.\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m0.\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;36m1.\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m1.\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     11\u001b[0m \u001b[0my\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 12\u001b[0;31m \u001b[0mclf\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mMLPClassifier\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0malgorithm\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'l-bfgs'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0malpha\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m1e-5\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mhidden_layer_sizes\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m5\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m2\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrandom_state\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     13\u001b[0m \u001b[0mclf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     14\u001b[0m \u001b[0mclf\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: __init__() got an unexpected keyword argument 'algorithm'"
     ]
    }
   ],
   "source": [
    "# imports\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# this allows plots to appear directly in the notebook\n",
    "%matplotlib inline\n",
    "\n",
    "from sklearn.neural_network import MLPClassifier\n",
    "\n",
    "X = [[0., 0.], [1., 1.]]\n",
    "y = [0, 1]\n",
    "clf = MLPClassifier(algorithm='l-bfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)\n",
    "clf.fit(X, y) \n",
    "clf"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Theano version 0.8.2\n",
      "theano is installed in /Applications/anaconda/lib/python2.7/site-packages/theano\n",
      "NumPy version 1.10.1\n",
      "NumPy relaxed strides checking option: True\n",
      "NumPy is installed in /Applications/anaconda/lib/python2.7/site-packages/numpy\n",
      "Python version 2.7.11 |Anaconda 2.4.1 (x86_64)| (default, Dec  6 2015, 18:57:58) [GCC 4.2.1 (Apple Inc. build 5577)]\n",
      "nose version 1.3.7\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Applications/anaconda/lib/python2.7/site-packages/theano/misc/pycuda_init.py:34: UserWarning: PyCUDA import failed in theano.misc.pycuda_init\n",
      "  warnings.warn(\"PyCUDA import failed in theano.misc.pycuda_init\")\n",
      "EE...........E..../Applications/anaconda/lib/python2.7/site-packages/theano/compile/profilemode.py:84: UserWarning: DEPRECATION WARNING: The ProfileMode is deprecated. Use the Theano flags/parameter to theano.function 'profile=True' instead of 'mode=ProfileMode'\n",
      "  \"DEPRECATION WARNING: The ProfileMode is deprecated. \"\n",
      "...../Applications/anaconda/lib/python2.7/site-packages/numpy/lib/nanfunctions.py:326: RuntimeWarning: All-NaN slice encountered\n",
      "  warnings.warn(\"All-NaN slice encountered\", RuntimeWarning)\n",
      "/Applications/anaconda/lib/python2.7/site-packages/numpy/lib/nanfunctions.py:227: RuntimeWarning: All-NaN axis encountered\n",
      "  warnings.warn(\"All-NaN axis encountered\", RuntimeWarning)\n",
      ".E........E.............................../Applications/anaconda/lib/python2.7/site-packages/theano/gof/vm.py:818: UserWarning: CVM does not support memory profile, using Stack VM.\n",
      "  'CVM does not support memory profile, using Stack VM.')\n",
      "...........SS.............INFO (theano.gof.compilelock): Waiting for existing lock by process '1945' (I am process '1815')\n",
      "INFO (theano.gof.compilelock): To manually release the lock, delete /Users/jayurbain/.theano/compiledir_Darwin-14.5.0-x86_64-i386-64bit-i386-2.7.11-64/lock_dir\n",
      "..............................................E...................................................................................INFO (theano.gof.compilelock): Waiting for existing lock by process '1945' (I am process '1815')\n",
      "INFO (theano.gof.compilelock): To manually release the lock, delete /Users/jayurbain/.theano/compiledir_Darwin-14.5.0-x86_64-i386-64bit-i386-2.7.11-64/lock_dir\n",
      "INFO (theano.gof.compilelock): Waiting for existing lock by process '1945' (I am process '1815')\n",
      "INFO (theano.gof.compilelock): To manually release the lock, delete /Users/jayurbain/.theano/compiledir_Darwin-14.5.0-x86_64-i386-64bit-i386-2.7.11-64/lock_dir\n",
      "INFO (theano.gof.compilelock): Waiting for existing lock by process '1945' (I am process '1815')\n",
      "INFO (theano.gof.compilelock): To manually release the lock, delete /Users/jayurbain/.theano/compiledir_Darwin-14.5.0-x86_64-i386-64bit-i386-2.7.11-64/lock_dir\n",
      "INFO (theano.gof.compilelock): Waiting for existing lock by process '1945' (I am process '1815')\n",
      "INFO (theano.gof.compilelock): To manually release the lock, delete /Users/jayurbain/.theano/compiledir_Darwin-14.5.0-x86_64-i386-64bit-i386-2.7.11-64/lock_dir\n",
      "INFO (theano.gof.compilelock): Waiting for existing lock by process '1945' (I am process '1815')\n",
      "INFO (theano.gof.compilelock): To manually release the lock, delete /Users/jayurbain/.theano/compiledir_Darwin-14.5.0-x86_64-i386-64bit-i386-2.7.11-64/lock_dir\n",
      ".SS.ES...SSSESEEEEEESSEESSESEESESSSEEEEEEEEE./Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/gpuarray/type.py:772: UserWarning: config.experimental.unpickle_gpu_on_cpu is set to True. Unpickling GpuArray as numpy.ndarray\n",
      "  \"config.experimental.unpickle_gpu_on_cpu is set to True. \"\n",
      ".EESEE......EE.....EE.......EEEEEEEEEEE..EEE.EEEE.....EEEE...E....E...........EEEEEEEEE......EEE......EEEE..........SEE..SSSSS.......S....E...\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/compile/tests/test_builders.py\", line 12, in <module>\n",
      "    from theano.tests import unittest_tools\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/compile/tests/test_debugmode.py\", line 13, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/compile/tests/test_function_module.py\", line 14, in <module>\n",
      "    from theano.tests.unittest_tools import SkipTest\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/compile/tests/test_ops.py\", line 6, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: test_sparse_input_aliasing_affecting_inplace_operations (theano.compile.tests.test_pfunc.Test_aliasing_rules)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/compile/tests/test_pfunc.py\", line 715, in test_sparse_input_aliasing_affecting_inplace_operations\n",
      "    from theano.sparse import enable_sparse\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sparse/__init__.py\", line 19, in <module>\n",
      "    from theano.sparse.basic import *\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sparse/basic.py\", line 25, in <module>\n",
      "    import theano.tests.unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/gof/tests/test_graph.py\", line 9, in <module>\n",
      "    from theano import (\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sparse/__init__.py\", line 19, in <module>\n",
      "    from theano.sparse.basic import *\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sparse/basic.py\", line 25, in <module>\n",
      "    import theano.tests.unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: theano.misc.tests.test_may_share_memory.test_may_share_memory_scipy\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/case.py\", line 197, in runTest\n",
      "    self.test(*self.arg)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/misc/tests/test_may_share_memory.py\", line 72, in test_may_share_memory_scipy\n",
      "    assert may_share_memory(a_, b_) == rep\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/misc/may_share_memory.py\", line 62, in may_share_memory\n",
      "    raise TypeError(\"may_share_memory support only ndarray\"\n",
      "TypeError: may_share_memory support only ndarray and scipy.sparse, CudaNdarray or GpuArray type\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_abstractconv.py\", line 4, in <module>\n",
      "    from theano.tensor.nnet.tests import test_abstract_conv\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/nnet/tests/test_abstract_conv.py\", line 10, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_blas.py\", line 7, in <module>\n",
      "    from theano.tests import unittest_tools\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_blocksparse.py\", line 6, in <module>\n",
      "    import theano.tests.unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_conv_cuda_ndarray.py\", line 24, in <module>\n",
      "    from theano.tests.unittest_tools import seed_rng, assert_allclose\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_cuda_ndarray.py\", line 12, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_cula.py\", line 5, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_dnn.py\", line 15, in <module>\n",
      "    import theano.tests.unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_fftconv.py\", line 5, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_gemmcorr3d.py\", line 6, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_mlp.py\", line 19, in <module>\n",
      "    import theano.tests.unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_nnet.py\", line 8, in <module>\n",
      "    import theano.tests.unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_opt.py\", line 15, in <module>\n",
      "    import theano.tensor.tests.test_nlinalg\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_nlinalg.py\", line 13, in <module>\n",
      "    from theano.tests.test_rop import break_op\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/test_rop.py\", line 16, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_tensor_op.py\", line 15, in <module>\n",
      "    from theano.tensor.nnet.tests import test_conv3d2d\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/nnet/tests/test_conv3d2d.py\", line 14, in <module>\n",
      "    import theano.tests.unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/gpuarray/tests/test_abstractconv.py\", line 5, in <module>\n",
      "    from theano.tensor.nnet.tests import test_abstract_conv\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/nnet/tests/test_abstract_conv.py\", line 10, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/gpuarray/tests/test_basic_ops.py\", line 13, in <module>\n",
      "    from theano.tensor.tests import test_basic\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_basic.py\", line 54, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/gpuarray/tests/test_blas.py\", line 8, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/gpuarray/tests/test_dnn.py\", line 4, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/gpuarray/tests/test_elemwise.py\", line 5, in <module>\n",
      "    from theano.tests.unittest_tools import SkipTest, assert_allclose\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/gpuarray/tests/test_neighbours.py\", line 1, in <module>\n",
      "    from theano.tensor.nnet.tests import test_neighbours\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/nnet/tests/test_neighbours.py\", line 10, in <module>\n",
      "    from theano.tests import unittest_tools\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/gpuarray/tests/test_nerv.py\", line 6, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/gpuarray/tests/test_nnet.py\", line 8, in <module>\n",
      "    import theano.tests.unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/gpuarray/tests/test_opt.py\", line 6, in <module>\n",
      "    from theano.tests import unittest_tools as utt, test_ifelse\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/gpuarray/tests/test_scan.py\", line 7, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/gpuarray/tests/test_subtensor.py\", line 6, in <module>\n",
      "    from theano.tensor.tests import test_subtensor\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_subtensor.py\", line 17, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/linalg/tests/test_linalg.py\", line 7, in <module>\n",
      "    from theano.tests.test_rop import break_op\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/test_rop.py\", line 16, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/tests/test_multinomial.py\", line 14, in <module>\n",
      "    import theano.tests.unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sandbox/tests/test_rng_mrg.py\", line 19, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/scalar/tests/test_basic.py\", line 20, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/scan_module/tests/test_scan.py\", line 23, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/scan_module/tests/test_scan_opt.py\", line 8, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sparse/__init__.py\", line 19, in <module>\n",
      "    from theano.sparse.basic import *\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sparse/basic.py\", line 25, in <module>\n",
      "    import theano.tests.unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/nnet/tests/speed_test_conv.py\", line 8, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/nnet/tests/test_abstract_conv.py\", line 10, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/nnet/tests/test_blocksparse.py\", line 9, in <module>\n",
      "    import theano.tests.unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/nnet/tests/test_bn.py\", line 2, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/nnet/tests/test_conv.py\", line 8, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/nnet/tests/test_conv3d.py\", line 6, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/nnet/tests/test_conv3d2d.py\", line 14, in <module>\n",
      "    import theano.tests.unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/nnet/tests/test_corr.py\", line 8, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/nnet/tests/test_neighbours.py\", line 10, in <module>\n",
      "    from theano.tests import unittest_tools\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/nnet/tests/test_nnet.py\", line 13, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/nnet/tests/test_sigm.py\", line 11, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/signal/tests/test_conv.py\", line 8, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/signal/tests/test_pool.py\", line 10, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_basic.py\", line 54, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_blas.py\", line 23, in <module>\n",
      "    from theano.tests import unittest_tools\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_blas_c.py\", line 19, in <module>\n",
      "    from theano.tests import unittest_tools\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_blas_scipy.py\", line 7, in <module>\n",
      "    from .test_blas import TestCase, gemm_no_inplace, TestBlasStrides\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_blas.py\", line 23, in <module>\n",
      "    from theano.tests import unittest_tools\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_complex.py\", line 6, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_elemwise.py\", line 20, in <module>\n",
      "    from theano.tests import unittest_tools\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_extra_ops.py\", line 7, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_fourier.py\", line 6, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_inc_subtensor.py\", line 4, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_keepdims.py\", line 8, in <module>\n",
      "    from theano.tests.unittest_tools import attr\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_nlinalg.py\", line 13, in <module>\n",
      "    from theano.tests.test_rop import break_op\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/test_rop.py\", line 16, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_opt.py\", line 60, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_opt_uncanonicalize.py\", line 11, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_raw_random.py\", line 5, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_shared_randomstreams.py\", line 15, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_sharedvar.py\", line 7, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_slinalg.py\", line 12, in <module>\n",
      "    from theano.tests.test_rop import break_op\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/test_rop.py\", line 16, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_sort.py\", line 2, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_subtensor.py\", line 17, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_var.py\", line 6, in <module>\n",
      "    import theano.tests.unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_xlogx.py\", line 7, in <module>\n",
      "    from . import test_basic as TT\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tensor/tests/test_basic.py\", line 54, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/typed_list/tests/test_basic.py\", line 14, in <module>\n",
      "    from theano import sparse\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sparse/__init__.py\", line 19, in <module>\n",
      "    from theano.sparse.basic import *\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/sparse/basic.py\", line 25, in <module>\n",
      "    import theano.tests.unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/typed_list/tests/test_type.py\", line 9, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/diverse_tests.py\", line 7, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/test_2nd_order_grads.py\", line 5, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/test_breakpoint.py\", line 4, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/test_gradient.py\", line 13, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/test_ifelse.py\", line 15, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "======================================================================\n",
      "ERROR: Failure: ImportError (No module named nose_parameterized)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/loader.py\", line 418, in loadTestsFromName\n",
      "    addr.filename, addr.module)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 47, in importFromPath\n",
      "    return self.importFromDir(dir_path, fqname)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/nose/importer.py\", line 94, in importFromDir\n",
      "    mod = load_module(part_fqname, fh, filename, desc)\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/test_rop.py\", line 16, in <module>\n",
      "    from theano.tests import unittest_tools as utt\n",
      "  File \"/Applications/anaconda/lib/python2.7/site-packages/theano/tests/unittest_tools.py\", line 7, in <module>\n",
      "    from nose_parameterized import parameterized\n",
      "ImportError: No module named nose_parameterized\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 408 tests in 99.242s\n",
      "\n",
      "FAILED (SKIP=26, errors=80)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<nose.result.TextTestResult run=408 errors=80 failures=0>"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import theano\n",
    "theano.test()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import theano\n",
    "from theano import tensor\n",
    "\n",
    "# declare two symbolic floating-point scalars\n",
    "a = tensor.dscalar()\n",
    "b = tensor.dscalar()\n",
    "\n",
    "# create a simple expression\n",
    "c = a + b\n",
    "\n",
    "# convert the expression into a callable object that takes (a,b)\n",
    "# values as input and computes a value for c\n",
    "f = theano.function([a,b], c)\n",
    "\n",
    "# bind 1.5 to 'a', 2.5 to 'b', and evaluate 'c'\n",
    "assert 4.0 == f(1.5, 2.5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<type 'numpy.ndarray'>\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "()"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "x = f(1.5, 2.5)\n",
    "print type(x)\n",
    "x.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
